/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cadastrar novo usuário */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autenticar usuário */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renovar access token usando refresh token (via cookie ou body) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerrar sessão e revogar refresh token */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter dados do usuário autenticado */
        get: operations["UsersController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar perfil e preferências do usuário */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar biblioteca de exercícios com filtros */
        get: operations["ExercisesController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter detalhes de um exercício */
        get: operations["ExercisesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar fichas prontas (templates) ou fichas do usuário (mine) */
        get: operations["WorkoutPlansController_findAll"];
        put?: never;
        /** Criar uma nova ficha de treino do zero */
        post: operations["WorkoutPlansController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter detalhes completos de uma ficha de treino */
        get: operations["WorkoutPlansController_findOne"];
        /** Atualizar completamente uma ficha do usuário */
        put: operations["WorkoutPlansController_update"];
        post?: never;
        /** Arquivar (soft delete) uma ficha de treino do usuário */
        delete: operations["WorkoutPlansController_archive"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-plans/{id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clonar uma ficha pronta da biblioteca gerando uma cópia do usuário */
        post: operations["WorkoutPlansController_clone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-plans/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Definir uma ficha como a ficha ativa do usuário */
        post: operations["WorkoutPlansController_activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar uma nova sessão de treino */
        post: operations["SessionsController_startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter a sessão de treino atualmente em andamento (se houver) */
        get: operations["SessionsController_getActiveSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter histórico de sessões de treino do usuário */
        get: operations["SessionsController_getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter detalhes de uma sessão de treino pelo ID */
        get: operations["SessionsController_getSessionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Registrar ou atualizar uma série de exercício (upsert idempotente) */
        put: operations["SessionsController_recordSet"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/sets/{setId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remover uma série registrada na sessão */
        delete: operations["SessionsController_deleteSet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalizar o treino, calcular volume, duração e conceder XP */
        post: operations["SessionsController_finishSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abandonar a sessão de treino em andamento */
        post: operations["SessionsController_abandonSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter lista de Recordes Pessoais (PRs) por exercício */
        get: operations["ProgressController_getPersonalRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter histórico de evolução de volume total levantado por data */
        get: operations["ProgressController_getVolumeProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gamification/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter lista de conquistas e status de progresso do usuário */
        get: operations["GamificationController_getAchievements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gamification/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter lista de missões diárias e progresso do usuário */
        get: operations["GamificationController_getMissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gamification/missions/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resgatar recompensa (XP + Moedas) de uma missão concluída */
        post: operations["GamificationController_claimMissionReward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example João Silva */
            name: string;
            /** @example joao@email.com */
            email: string;
            /** @example senha12345 */
            password: string;
            /**
             * @default HYPERTROPHY
             * @enum {string}
             */
            goal: "HYPERTROPHY" | "WEIGHT_LOSS" | "STRENGTH" | "CONDITIONING" | "HEALTH" | "OTHER";
            /**
             * @default America/Sao_Paulo
             * @example America/Sao_Paulo
             */
            timezone: string;
        };
        LoginDto: {
            /** @example joao@email.com */
            email: string;
            /** @example senha12345 */
            password: string;
        };
        RefreshTokenDto: {
            /** @description Refresh token opcional no body caso não esteja em cookie */
            refreshToken?: string;
        };
        UserStatsResponseDto: {
            xp: number;
            level: number;
            coins: number;
            currentStreak: number;
            longestStreak: number;
            lastWorkoutDate?: string;
            totalWorkouts: number;
            totalSets: number;
            totalVolumeKg: number;
            totalPRs: number;
        };
        UserResponseDto: {
            id: string;
            name: string;
            email: string;
            avatarUrl?: string;
            bio?: string;
            /** @enum {string} */
            goal: "HYPERTROPHY" | "WEIGHT_LOSS" | "STRENGTH" | "CONDITIONING" | "HEALTH" | "OTHER";
            timezone: string;
            activePlanId?: string;
            createdAt: string;
            stats?: components["schemas"]["UserStatsResponseDto"];
        };
        AuthResponseDto: {
            user: components["schemas"]["UserResponseDto"];
            /** @description Access Token JWT */
            accessToken: string;
        };
        ExerciseResponseDto: {
            id: string;
            slug: string;
            name: string;
            description: string;
            /** @enum {string} */
            primaryMuscle: "CHEST" | "BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "ABS" | "FULL_BODY";
            secondaryMuscles: ("CHEST" | "BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "ABS" | "FULL_BODY")[];
            /** @enum {string} */
            equipment: "BODYWEIGHT" | "DUMBBELL" | "BARBELL" | "MACHINE" | "CABLE" | "BAND" | "OTHER";
            /** @enum {string} */
            difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
            instructions: string[];
            imageUrl?: string;
            videoUrl?: string;
            isActive: boolean;
        };
        CreateWorkoutExerciseDto: {
            /** @example uuid-do-exercicio */
            exerciseId: string;
            /** @example 1 */
            order: number;
            /** @example 4 */
            sets: number;
            /** @example 8 */
            repsMin: number;
            /** @example 12 */
            repsMax: number;
            /**
             * @description Tempo de descanso em segundos
             * @example 90
             */
            restSeconds: number;
            /** @example Aumentar carga na última série */
            notes?: string;
        };
        CreateWorkoutDayDto: {
            /** @example A — Peito e Tríceps */
            name: string;
            /** @example 1 */
            order: number;
            /**
             * @description 0 (Dom) a 6 (Sáb)
             * @example 1
             */
            weekday?: number;
            exercises: components["schemas"]["CreateWorkoutExerciseDto"][];
        };
        CreateWorkoutPlanDto: {
            /** @example Minha Ficha Hipertrofia ABCD */
            name: string;
            /** @example Ficha focada em braços e peitoral */
            description?: string;
            /** @enum {string} */
            goal?: "HYPERTROPHY" | "WEIGHT_LOSS" | "STRENGTH" | "CONDITIONING" | "HEALTH" | "OTHER";
            /** @enum {string} */
            difficulty?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
            /** @example 4 */
            daysPerWeek: number;
            days: components["schemas"]["CreateWorkoutDayDto"][];
        };
        UpdateWorkoutPlanDto: {
            /** @example Minha Ficha Hipertrofia ABCD */
            name: string;
            /** @example Ficha focada em braços e peitoral */
            description?: string;
            /** @enum {string} */
            goal?: "HYPERTROPHY" | "WEIGHT_LOSS" | "STRENGTH" | "CONDITIONING" | "HEALTH" | "OTHER";
            /** @enum {string} */
            difficulty?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
            /** @example 4 */
            daysPerWeek: number;
            days: components["schemas"]["CreateWorkoutDayDto"][];
        };
        WorkoutExerciseResponseDto: {
            id: string;
            dayId: string;
            exerciseId: string;
            exercise: components["schemas"]["ExerciseResponseDto"];
            order: number;
            sets: number;
            repsMin: number;
            repsMax: number;
            restSeconds: number;
            notes?: string;
        };
        WorkoutDayResponseDto: {
            id: string;
            planId: string;
            name: string;
            order: number;
            weekday?: number;
            exercises: components["schemas"]["WorkoutExerciseResponseDto"][];
        };
        WorkoutPlanResponseDto: {
            id: string;
            slug?: string;
            name: string;
            description?: string;
            /** @enum {string} */
            goal?: "HYPERTROPHY" | "WEIGHT_LOSS" | "STRENGTH" | "CONDITIONING" | "HEALTH" | "OTHER";
            /** @enum {string} */
            difficulty?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
            daysPerWeek: number;
            isTemplate: boolean;
            ownerId?: string;
            sourcePlanId?: string;
            createdAt: string;
            days?: components["schemas"]["WorkoutDayResponseDto"][];
        };
        WorkoutSetResponseDto: {
            id: string;
            sessionId: string;
            exerciseId: string;
            exerciseOrder: number;
            setNumber: number;
            weightKg: number;
            reps: number;
            completed: boolean;
            isPR: boolean;
            completedAt?: string;
        };
        WorkoutSessionResponseDto: {
            id: string;
            userId: string;
            planId?: string;
            dayId?: string;
            planName: string;
            dayName: string;
            /** @enum {string} */
            status: "IN_PROGRESS" | "COMPLETED" | "ABANDONED";
            startedAt: string;
            finishedAt?: string;
            durationSec?: number;
            totalVolumeKg: number;
            xpEarned: number;
            coinsEarned: number;
            sets: components["schemas"]["WorkoutSetResponseDto"][];
        };
        PersonalRecordDto: {
            exerciseId: string;
            exerciseName: string;
            primaryMuscle: string;
            /** @example 100 */
            maxWeightKg: number;
            /** @example 10 */
            maxReps: number;
            /**
             * @description Estimativa de 1RM (Carga Máxima de 1 repetição) em kg
             * @example 133.3
             */
            estimated1RM: number;
            achievedAt: string;
        };
        VolumeChartPointDto: {
            /** @example 2026-10-04 */
            date: string;
            /** @example 2450 */
            totalVolumeKg: number;
            /** @example 1 */
            sessionCount: number;
        };
        AchievementResponseDto: {
            id: string;
            code: string;
            name: string;
            description: string;
            category: string;
            xpReward: number;
            coinsReward: number;
            unlocked: boolean;
            unlockedAt: string | null;
            progress: number;
            target: number;
        };
        MissionResponseDto: {
            id: string;
            code: string;
            title: string;
            description: string;
            type: string;
            xpReward: number;
            coinsReward: number;
            progress: number;
            target: number;
            completed: boolean;
            claimed: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    ExercisesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponseDto"][];
                };
            };
        };
    };
    ExercisesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponseDto"];
                };
            };
        };
    };
    WorkoutPlansController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanResponseDto"][];
                };
            };
        };
    };
    WorkoutPlansController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanResponseDto"];
                };
            };
        };
    };
    WorkoutPlansController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanResponseDto"];
                };
            };
        };
    };
    WorkoutPlansController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanResponseDto"];
                };
            };
        };
    };
    WorkoutPlansController_archive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkoutPlansController_clone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanResponseDto"];
                };
            };
        };
    };
    WorkoutPlansController_activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_startSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponseDto"];
                };
            };
        };
    };
    SessionsController_getActiveSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponseDto"];
                };
            };
        };
    };
    SessionsController_getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_getSessionById: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponseDto"];
                };
            };
        };
    };
    SessionsController_recordSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponseDto"];
                };
            };
        };
    };
    SessionsController_deleteSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_finishSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponseDto"];
                };
            };
        };
    };
    SessionsController_abandonSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProgressController_getPersonalRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalRecordDto"][];
                };
            };
        };
    };
    ProgressController_getVolumeProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeChartPointDto"][];
                };
            };
        };
    };
    GamificationController_getAchievements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementResponseDto"][];
                };
            };
        };
    };
    GamificationController_getMissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionResponseDto"][];
                };
            };
        };
    };
    GamificationController_claimMissionReward: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
